<?php
/**
 * Created by PhpStorm.
 * User: 毛阿毛
 * Date: 2019/10/23
 * Time: 16:46
 */
namespace app\common\helpers;

use yii\helpers\Console;

class ConsoleHelper extends Console
{
    public static function output($string = null)
    {
        return parent::output(date('Y-m-d H:i:s').'>>>>>>'.$string); // TODO: Change the autogenerated stub
    }
}